name: Find Current Pull Request
author: jwalton
description: Find a PR associated with the current commit.
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.  Defaults to github provided token.
    required: true
    default: ${{ github.token }}
  sha:
    description: Sha to get PR for.  Defaults to current sha.
    required: true
    default: ${{ github.sha }}
outputs:
  number:
    description: The PR's number if the PR was found (e.g. '345' for #345)
  title:
    description: The PR's title if the PR was found
  body:
    description: The PR's body if the PR was found
runs:
  using: node12
  main: 'main.js'
branding:
  icon: git-pull-request
  color: blue
